# Generated by Django 3.0.3 on 2020-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200228_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
