# Generated by Django 3.0.3 on 2020-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_model_label_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
