# Generated by Django 3.0.3 on 2020-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_model_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
