# Generated by Django 3.0.3 on 2020-05-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_model_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['status']},
        ),
    ]
