# Generated by Django 3.0.3 on 2020-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200228_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
