# Generated by Django 3.0.3 on 2020-05-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200228_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='boxes',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='captions',
            field=models.TextField(max_length=360, null=True),
        ),
    ]
