# Generated by Django 3.0.3 on 2020-05-17 03:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200516_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='boxes',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='captions',
            field=jsonfield.fields.JSONField(),
        ),
    ]
